### ISSUE TITLE
Option to process tasks 1 for the current day only (no future)

### ISSUE THREAD

**Issue by sovcik** [jsdev2015/recgtasks#36]
The idea is to keep to-do list "clean" without any future tasks.

**Comment by nilesmeng** [comment]
Thanks for making this app. Your "keep clean" method (= process 1 day ahead instead of 2 weeks+) is the only thing i am missing. It would be great if that could be implemented - I could then throw out my Outlook client ;-).
Thanks,

**Comment by sovcik** [comment]
Hi, does that mean you don't want to see tasks which will be due in more
than one day?
How do you work (=visualize) with Google tasks? Do you use some 3rd party
app or standard Google Calendar? Because Google Caledar can show only due
"today", which would most likely solve your issue.

**Comment by nilesmeng** [comment]
You are absolutely right – I just checked it out, using the Google calendar to administer the tasks. 

Your script will work as it is for me :)

 

Thanks for your help!

**Comment by sovcik** [comment]
Glad to hear that. :-)
Enjoy.

J.

**Comment by ghost** [comment]
Hi, will this feature be made available? (to just see the tasks for the current day, not future days)
Thanks

**Comment by sovcik** [comment]
It's not planned for the near future yet.

Which tool you use to visualize your tasks? Wouldn't it be possible to set filter to "today tasks"?
Optionally you can set "Processing Date Range" in Settings to shorter range e.g. two weeks.
Well, that would still result in seeing tasks for the following 14 days...

**Comment by ghost** [comment]
The tool I am using is just looking at the tasks on the URL:

https://mail.google.com/tasks/canvas

I don't put dates on any of my tasks. I manage my tasks by priority, not by
date. I order them by "My order" not by "date".

I just want certain tasks to appear at the top of my list every day so that
I can complete them. I don't want to see weeks of those repeating tasks
into the future, that would just fill my task list with tasks that are not
relevant for the current day.

If you have this option "Processing Date Range" with the minimum option as
14 days, could you please just add the option "1 day" to that "Processing
Date Range" option?

Because we just want to see the current day's tasks, not tasks into the
future.

I'm talking about tasks that are only relevant for the current day and can
only be completed in the current day.

here are some examples:
Walk the dog today.
Take your vitamins today.
Check the mail.
Go for a run today.
Go to the gym.
Check the server log today.
Etc
ᐧ

**Comment by sovcik** [comment]
Ok, let me look at it :-)

**Comment by ghost** [comment]
Ok, great! Thank you for that! :)
ᐧ

**Comment by sovcik** [comment]
Ok, it should be there. I added possibility to set Processing Range to 1 day.
But you have to remove all already created future tasks manually...
Then you can run task processing manually from the main screen.

**Comment by sovcik** [comment]
Well, thinking of it now... this means you will still see one day into the future... +1 day = tomorrow.
I think you meant today only, right?

**Comment by ghost** [comment]
Brilliant!

Thank you for this, I will try it out.

Thanks
ᐧ

**Comment by ghost** [comment]
Yes, that's right. I only wanted the tasks that are currently scheduled for
the current day to appear on the current day.

So would it actually be a day = 0 option?
ᐧ

**Comment by sovcik** [comment]
Yes, that most likely will be the solution. Let me try.

**Comment by sovcik** [comment]
Ok, done. Changed +1 day to "today". Seems to work :-)

**Comment by ghost** [comment]
Ok, great. Thank you.

I will give it a try.
ᐧ

**Comment by ghost** [comment]
It looks like it works perfectly I just wanted to say thanks so much for
taking the time to make this adjustment and also your other options are
really well thought through and worked brilliantly this is an awesome
extension thank you

**Comment by sovcik** [comment]
Glad you like it. Enjoy!
