### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by ghost** [jsdev2015/recgtasks#40]
Please see attached screenshot for 

Summary of failures for Google Apps Script: Recurrent Tasks for GTasks

![image](https://user-images.githubusercontent.com/140161/34902795-d5a39070-f876-11e7-8bf2-19221949693c.png)

**Comment by sovcik** [comment]
Hi, due to "various reasons" there is approx. 0.4% of Google API requests failing. So you are going to receive similar messages maybe once per month.

Fortunately you don't have to worry - tasks are processed every hour (for now) and so if one run fails, the next will go through just fine.

And yes, I might implement some error handling so similar messages do not bother users :-)

**Comment by sovcik** [comment]
I have opened #41 for implementing error handling on task.insert API.

**Comment by ghost** [comment]
Sounds great, thanks!
ᐧ

**Comment by sovcik** [comment]
You are welcome!
